#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${NEURAI_DATADIR:-/data}"
mkdir -p "$DATA_DIR"

cat > "$DATA_DIR/neurai.conf" <<EOF
# Generated by Docker entrypoint — do not edit manually
testnet=${NEURAI_TESTNET:-1}

# RPC
rpcuser=${NEURAI_RPC_USER:-neurai}
rpcpassword=${NEURAI_RPC_PASSWORD:-changeme}
rpcallowip=${NEURAI_RPC_ALLOW_IP:-0.0.0.0/0}
rpcport=${NEURAI_RPC_PORT:-19101}
rpcservertimeout=${NEURAI_RPC_TIMEOUT:-240}
rpcworkqueue=${NEURAI_RPC_WORKQUEUE:-64}
rpcthreads=${NEURAI_RPC_THREADS:-8}
server=1

# Network
listen=${NEURAI_LISTEN:-0}
rest=${NEURAI_REST:-1}

# Indexes
txindex=${NEURAI_TXINDEX:-1}
assetindex=${NEURAI_ASSETINDEX:-1}
addressindex=${NEURAI_ADDRESSINDEX:-1}
timestampindex=${NEURAI_TIMESTAMPINDEX:-1}
spentindex=${NEURAI_SPENTINDEX:-1}
pubkeyindex=${NEURAI_PUBKEYINDEX:-1}

# Wallet — disabled by default, set NEURAI_DISABLE_WALLET=0 to enable
disablewallet=${NEURAI_DISABLE_WALLET:-1}

# Log — shrink debug.log automatically when it grows too large
shrinkdebugfile=1

# Docker — run in foreground (daemon=1 breaks the container lifecycle)
daemon=0
EOF

echo "[entrypoint] neurai.conf written to $DATA_DIR/neurai.conf"
exec neuraid -datadir="$DATA_DIR" "$@"
